/* de la BD y conexion a ella*/
CREATE OR REPLACE DATABASE CONTACTOS;
USE AGENDA;


/*Tabla contacto*/
CREATE TABLE CONTACTOS(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  NOMBRE VARCHAR(30) NOT NULL,
  MAIL VARCHAR(30) NOT NULL UNIQUE
);


/*Tabla Relacion*/
CREATE TABLE RELACION(
ID_CONOCEDOR INT ,
ID_CONOCIDO INT ,
PRIMARY KEY(ID_CONOCEDOR,ID_CONOCIDO),
FOREIGN KEY(ID_CONOCEDOR) REFERENCES CONTACTOS(ID) ON DELETE CASCADE
                                                    ON UPDATE CASCADE,
FOREIGN KEY(ID_CONOCIDO) REFERENCES CONTACTOS(ID) ON DELETE CASCADE
                                                    ON UPDATE CASCADE
);

//*

consulta para sacar los conocidos de un contacto
*/

SELECT relacion.ID_CONOCEDOR, Contactos.NOMBRE as conocido
 from relacion ,contactos
 where contactos.id = relacion.ID_CONOCIDO and ID_CONOCEDOR=2
 ORDER BY relacion.ID_CONOCEDOR

/*Insercion de datos a la bd*/

/*ALTER TABLE nombre_tabla AUTO_INCREMENT=1*/


INSERT INTO CONTACTOS (NOMBRE,MAIL) VALUES ('LUKE','LUKESKYWALKER@JEDI.COM');
INSERT INTO CONTACTOS (NOMBRE,MAIL) VALUES ('LEIA ORGANA','PRINCESITA@RESISTENCE.COM');
INSERT INTO CONTACTOS (NOMBRE,MAIL) VALUES ('DARTH VADER','MALOTE@DEATHSTAR.COM');
INSERT INTO CONTACTOS (NOMBRE,MAIL) VALUES ('YODA','COM@THEFORCE.YODA');
INSERT INTO CONTACTOS (NOMBRE,MAIL) VALUES ('HAN','TOYSOLO@ISHOTFIRST.COM');
INSERT INTO CONTACTOS (NOMBRE,MAIL) VALUES ('CHEWBACCA','CHEW@FALCON.COM');
INSERT INTO CONTACTOS (NOMBRE,MAIL) VALUES ('C3P0','C3P0@CYBOT.COM');
INSERT INTO CONTACTOS (NOMBRE,MAIL) VALUES ('R2D2','R2D2@.AUTOMATION.COM');
INSERT INTO CONTACTOS (NOMBRE,MAIL) VALUES ('OBI WAN KENOBI','TITOBEN@HERMIT.COM');
INSERT INTO CONTACTOS (NOMBRE,MAIL) VALUES ('FINN','FN2187@STORMTROOPER.COM');



INSERT INTO RELACION (ID_CONOCEDOR,ID_CONOCIDO) VALUES (1,2);
INSERT INTO RELACION (ID_CONOCEDOR,ID_CONOCIDO) VALUES (1,2);
INSERT INTO RELACION (ID_CONOCEDOR,ID_CONOCIDO) VALUES (1,3);
INSERT INTO RELACION (ID_CONOCEDOR,ID_CONOCIDO) VALUES (1,4);
INSERT INTO RELACION (ID_CONOCEDOR,ID_CONOCIDO) VALUES (1,5);
INSERT INTO RELACION (ID_CONOCEDOR,ID_CONOCIDO) VALUES (1,6);
INSERT INTO RELACION (ID_CONOCEDOR,ID_CONOCIDO) VALUES (1,7);
INSERT INTO RELACION (ID_CONOCEDOR,ID_CONOCIDO) VALUES (1,8);
INSERT INTO RELACION (ID_CONOCEDOR,ID_CONOCIDO) VALUES (1,9);
INSERT INTO RELACION (ID_CONOCEDOR,ID_CONOCIDO) VALUES (2,1);
INSERT INTO RELACION (ID_CONOCEDOR,ID_CONOCIDO) VALUES (2,3);
INSERT INTO RELACION (ID_CONOCEDOR,ID_CONOCIDO) VALUES (2,4);
INSERT INTO RELACION (ID_CONOCEDOR,ID_CONOCIDO) VALUES (3,1);
INSERT INTO RELACION (ID_CONOCEDOR,ID_CONOCIDO) VALUES (3,2);
INSERT INTO RELACION (ID_CONOCEDOR,ID_CONOCIDO) VALUES (3,4);
INSERT INTO RELACION (ID_CONOCEDOR,ID_CONOCIDO) VALUES (3,7);
INSERT INTO RELACION (ID_CONOCEDOR,ID_CONOCIDO) VALUES (3,9);
INSERT INTO RELACION (ID_CONOCEDOR,ID_CONOCIDO) VALUES (4,1);
INSERT INTO RELACION (ID_CONOCEDOR,ID_CONOCIDO) VALUES (4,6);
INSERT INTO RELACION (ID_CONOCEDOR,ID_CONOCIDO) VALUES (4,8);
INSERT INTO RELACION (ID_CONOCEDOR,ID_CONOCIDO) VALUES (5,1);
INSERT INTO RELACION (ID_CONOCEDOR,ID_CONOCIDO) VALUES (6,7);
INSERT INTO RELACION (ID_CONOCEDOR,ID_CONOCIDO) VALUES (6,8);
INSERT INTO RELACION (ID_CONOCEDOR,ID_CONOCIDO) VALUES (7,8);
INSERT INTO RELACION (ID_CONOCEDOR,ID_CONOCIDO) VALUES (8,7);












